### ISSUE TITLE
Which license does puyoai use?

### ISSUE THREAD

**Issue by gecko655** [puyoai/puyoai#89]
人類戦お疲れ様でした。ニコニコで大変楽しく視聴させていただきました。

このリポジトリにはライセンス表示がないようなのですが、なにか特定のライセンスを決めていますか？

ざっとリポジトリ内を"license"で全文検索したところ、テレビ画面のキャプチャに使っている[easycap-somagic-linux](https://code.google.com/p/easycap-somagic-linux/ "")がGPLv2、[googletest](https://code.google.com/p/googletest/ "")が修正BSD、その他のコードでライセンスのあるものはすべてMITでした。
もし、ライセンスを特に決めていないようでしたら、GPLがあるためGPL互換のライセンスが適切かと思います。いかがでしょうか？

**Comment by mayah** [comment]
If no one objects, I'd like to use MIT license by default. I don't like to use GPL.
However, license under src/cpu/* can be overwritten by each AI developers.

**Comment by mayah** [comment]
Note: Currently if we build with capture/, the entire license must be GPL, since it contains GPL code. However, if we build without capture (to be precise, somagic_source), the entire license does not need to be GPL.

Since somagic driver does not work on AC (I'm not sure why, but the somagic chip cannot convert the AC signals correctly), I'd like to remove it. After that commit, I believe we don't have any GPL code?

**Comment by mayah** [comment]
Ah, deprecated/ contains some GPL code :( We need to remove them.
We need to define the range of our code. Maybe we need to move all our codes to src/, and have LICENSE under src/ ? The other resources should be out of scope.

**Comment by mayah** [comment]
Removed deprecated/ and somagic source. So maybe we don't have GPL code any more?

**Comment by peria** [comment]
verified

**Comment by mayah** [comment]
added LICENSE.
