### ISSUE TITLE
Consider migrate documents to Wiki

### ISSUE THREAD

**Issue by peria** [puyoai/puyoai#92]
We already have some documents written in mark-down texts.  However, it is a heavy task to update those files and it is difficult to check if a file is written correctly in mark-down format.
So I suggest to move them to Wiki of this repository.

Pros:
* easy to check correctness
* no need to commit (no noise in commit list)

Cons:
* need network
* less custamizable

**Comment by peria** [comment]
Of course, we must keep some information in /README.md.

**Comment by mayah** [comment]
I'm using Atom to write and preview markdown text. Live update is possible, so I don't have such stress.

Anyway, since wiki itself is maintained with git, we can clone/push/pull the wiki. So, we can update wiki without network?

However, I'm feeling maintaining two git is not good... Not sure which is better. 
Might be ok to use git submodule to import wiki to wiki/ or doc/wiki ?

**Comment by peria** [comment]
We can edit Wiki directly on browsers.
In this situation, we don't have to pay attention to manage git for wiki, even though it is under a git system.

**Comment by mayah** [comment]
Basically I want to update the document offline... Writing everything on the browser is 苦行

**Comment by peria** [comment]
Hmm, then close this issue as wont fix.
mayah's agreement is required to go forward.

**Comment by mayah** [comment]
Actually markdown file can be edited in browser (even if it's not wiki!)
If you'd like to update the markdown on browser, you can use it?

c.f. http://tech.a-listers.jp/2011/04/27/githubでブラウザ上からファイルの編集が可能になり/

**Comment by peria** [comment]
Ooh hoo!
Thank you for the information!
